move pio parameters to nuopc.runconfig input file
ESCOMP/CMEPS pull request #275
Opened 2022-03-17 20:21 UTC by jedwards4b

### Description of changes
Update shr_pio_mod, removing mct centric initialization.
Improve logging and make sure logs go to the correct component.

### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

2022-03-23 17:45 UTC, mvertens requested changes

2022-03-23 17:45 UTC, mvertens commented on mediator/med_io_mod.F90
> +    print *,__FILE__,__LINE__,'PIO type, format:',pio_iotype, pio_ioformat
Please remove this!

2022-03-30 21:42 UTC, mvertens commented
@jedwards4b - are we ready to merge this?

2022-03-31 19:53 UTC, jedwards4b commented
@mvertens There is a failing test I need to fix first, see: https://github.com/ESMCI/cime/pull/4199

2022-04-14 03:47 UTC, mvertens commented
@jedwards4b - please summarize the testing you did for this PR. I cannot accept that before then. Also please fill in a summary of the user interface changes and other requested input for the PR.

2022-04-15 16:55 UTC, mvertens approved these changes

2022-04-15 16:56 UTC, merged