enable asyncio using pio
ESCOMP/CMEPS pull request #325
Opened 2022-12-06 22:58 UTC by jedwards4b

### Description of changes 
Allows IO tasks to be independent of compute tasks in cesm

### Specific notes
(testing in progress)
Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

2022-12-07 23:56 UTC, billsacks requested changes
Thanks a lot for your work on this @jedwards4b ! This is a really exciting new feature!

I have a few comments below. Most of them are minor & easy. The main one that might be more involved is my long comment, particularly the second paragraph starting "Part of what I'm wondering about here...". Let me know if you'd like to talk about this.

2022-12-08 14:54 UTC, jedwards4b commented on cesm/driver/ensemble_driver.F90
> +    ! ModifyCplLists is a NUOPC specialization which happens after Advertize but before Realize
done

2022-12-08 14:55 UTC, jedwards4b commented on cesm/driver/ensemble_driver.F90
> +          endif
I think that you may be right here.  I'll create a few scenarios to test this and put in a fix if needed.

2022-12-08 14:55 UTC, jedwards4b commented on cesm/driver/esm.F90
> +!    if (chkerr(rc,__LINE__,u_FILE_u)) return
done

2022-12-08 14:55 UTC, jedwards4b commented on cesm/driver/esm.F90
> +!    if (chkerr(rc,__LINE__,u_FILE_u)) return
done

2022-12-08 14:56 UTC, jedwards4b commented on cesm/driver/esm_time_mod.F90
> +    read(cvalue,*) glc_avg_period
done

2022-12-08 14:56 UTC, jedwards4b commented on cesm/nuopc_cap_share/driver_pio_mod.F90
> +          call NUOPC_CompAttributeGet(gcomp(i), name="pio_async_interface", value=cval, rc=rc)
thanks for spotting that.

2022-12-09 18:18 UTC, jedwards4b commented on cesm/driver/ensemble_driver.F90
> +          endif
It's difficult to get to the pio_async_interface flags at this point in the fortran and I am thinking about implementing something in the buildnml instead - would that be acceptable?

2022-12-12 16:16 UTC, DeniseWorthen commented on mediator/med.F90
> +  private AdvertiseFields ! advertise fields
Thanks for these.

2022-12-12 16:16 UTC, DeniseWorthen approved these changes
All UWM test pass.

2022-12-12 16:38 UTC, uturuncoglu approved these changes

2023-01-26 14:28 UTC, jedwards4b commented
Retested prealpha against alpha12b
```
 ./cs.status.20230125_114302_bxq3t5 -f | grep -v NLCOMP | grep -v BFAIL
20230125_114302_bxq3t5: 87 tests
    FAIL DAE_N2_D_Lh12_Vmct.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.clm-DA_multidrv TPUTCOMP Error: TPUTCOMP: Computation time increase > 25% from baseline
    FAIL ERP_D_Ln9_Vnuopc.C48_C48_mg17.QPC6.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=245
    FAIL ERP_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel.cam-outfrq1d BASELINE cesm2_3_alpha12b: DIFF
    FAIL IRT_C3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio RUN time=7222
    PEND IRT_C3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio COMPARE_base_restart
    FAIL MCC.f19_g17.B1850.cheyenne_intel.allactive-defaultiomi RUN time=7231
    PEND MCC.f19_g17.B1850.cheyenne_intel.allactive-defaultiomi COMPARE_base_single_instance
    FAIL MCC_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling RUN time=5427
    PEND MCC_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling COMPARE_base_single_instance
    FAIL SMS_D_Ld1_PS.f09_g17.I1850Clm50BgcSpinup.cheyenne_intel.clm-cplhist RUN time=46
    FAIL SMS_D_Ln9_Vnuopc_P720x1.ne0CONUSne30x8_ne0CONUSne30x8_mt12.FCnudged.cheyenne_intel.cam-outfrq9s RUN time=1216
    FAIL SMS_Ld1_P144_D.T62_g17.C.cheyenne_intel.pop-144blocks_320x384_spacecurve RUN time=43244
    FAIL SMS_Ld2_P80_D.T62_g37.C1850ECO.cheyenne_intel.pop-ecosys_81blocks_100x116_spacecurve RUN time=43257
```
@fischer-ncar these all look like failures in alpha12b - can I go ahead and merge?

2023-01-26 16:21 UTC, fischer-ncar commented
Yes, those are expected failures.  You can go ahead and merge.

2023-01-26 16:22 UTC, merged