fix bug in ocn2glc_coupling and add blom
ESCOMP/CMEPS pull request #484
Opened 2024-07-11 12:01 UTC by mvertens

### Description of changes
This adds blom as another ocean component in cime_config.

### Specific notes
This adds blom as another ocean component in cime_config and also fixes the query of the logical variable for ocn2glc coupling in esmFldsExchange_cesm.F90.

Contributors other than yourself, if any: None

CMEPS Issues Fixed: No

Are changes expected to change answers? bfb

Any User Interface Changes (namelist or namelist defaults changes)? No

### Testing performed
Verified that ocn2glc coupling is working correctly with blom.

2024-07-11 22:42 UTC, billsacks requested changes
A couple of questions / minor (I hope) requests below.

2024-07-11 22:42 UTC, billsacks commented on cime_config/config_component_cesm.xml
> +      <!-- NOTE: urrently a NUOPC runseqence cannot be generated with the ATM_NCPL < OCN_NCPL -->
Minor typo: urrently -> currently

2024-07-11 22:42 UTC, billsacks commented on cime_config/config_component_cesm.xml
> +
Are these only valid for BLOM currently? If so, I feel this should at least be documented. Ideally they would only be available for BLOM, or there would be an error check to ensure they aren't set for other models, but I suspect that's hard... if it's true that those would be hard to do, then I think it's fine to just add in the description something like "Only available with the BLOM ocean model" or something like that.

2024-07-12 07:33 UTC, mvertens commented
@billsacks - thanks so much for your review. I've addressed the issues you raised.

2024-07-12 16:20 UTC, billsacks approved these changes
Looks good - thank you!

2024-07-12 18:30 UTC, merged